### ISSUE TITLE
无法使用，希望添加linux的环境配置教程

### ISSUE THREAD

**Issue by SuperEndermanSM** [Cyenoch/QuQ#2]
vsesm@vsesm-PC:~/Desktop$ yarn
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

**Comment by MicroCBer** [comment]
草（
你先git clone把源代码下下来（最好下另一个分支，主分支还用不了，另一个效率差但是能用），文件比较大最好挂个代理
然后cd进源码目录，npm i或者yarn补全库

然后npm run dev
前提是你要装好npm和git，我建议用npm啦，毕竟yarn我也没用过不是（
npm可以装个cnpm加速安装（不然慢死你），方法百度有，搜cnpm即可

**Comment by MicroCBer** [comment]
另外，感谢支持～

**Comment by MicroCBer** [comment]
如果不满意别直接退了，毕竟这是个我赶出来的半成品（
真的好用的可能过几天在主分支发

**Comment by SuperEndermanSM** [comment]
> 
> 
> 草（
> 你先git clone把源代码下下来（最好下另一个分支，主分支还用不了，另一个效率差但是能用），文件比较大最好挂个代理
> 然后cd进源码目录，npm i或者yarn补全库
> 
> 然后npm run dev
> 前提是你要装好npm和git，我建议用npm啦，毕竟yarn我也没用过不是（
> npm可以装个cnpm加速安装（不然慢死你），方法百度有，搜cnpm即可
我直接码云镜像过去下的，速度很快

**Comment by SuperEndermanSM** [comment]
> 
> 
> 草（
> 你先git clone把源代码下下来（最好下另一个分支，主分支还用不了，另一个效率差但是能用），文件比较大最好挂个代理
> 然后cd进源码目录，npm i或者yarn补全库
> 
> 然后npm run dev
> 前提是你要装好npm和git，我建议用npm啦，毕竟yarn我也没用过不是（
> npm可以装个cnpm加速安装（不然慢死你），方法百度有，搜cnpm即可

我直接码云镜像过去下的，速度很快

**Comment by SuperEndermanSM** [comment]
vsesm@vsesm-PC:~/Desktop$ npm run dev
npm WARN npm npm does not support Node.js v10.19.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! path /home/vsesm/Desktop/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/vsesm/Desktop/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vsesm/.npm/_logs/2020-07-24T23_45_08_674Z-debug.log

**Comment by SuperEndermanSM** [comment]
没事了，npm i不是npm -i啊
